- doc/book/migration.md
- src/ServiceManager.php
- test/ServiceManagerTest.php
This patch re-instates invokables, but not by re-adding the original functionality, but instead modifing the `configure()` method to create `factories` and `aliases` configuration from the `invokables` configuration, using the following rules:
- If the service name and class name match, it creates a `factories` entry, mapping the service name to an `InvokableFactory`.
- If the service name and class name *do not* match, it creates an `aliases` entry mapping the service name to the class name, and a `factories` entry, mapping the class name to an `InvokableFactory`.
This is exactly what was previously recommended in the migration guide; the patch simply automates it from the configuration.
Using this would remove the largest BC break for end-users.
> Re-instate invokables

- doc/book/migration.md
- src/Config.php
- src/ConfigInterface.php
- test/ConfigTest.php
This patch re-instates the `ConfigInterface` and `Config` class, with updates to follow the other changes in the component:
- `ConfigInterface::configureServiceManager()` is now specified as returning a *new* `ServiceManager` instance.
- `Config` now aggregates configuration and passes it to `ServiceManager::withConfig()`, returning the resulting cloned instance.
This was done due to the copius usage of both within components, to facilitate migration.
> Re-instate config features

- doc/book/migration.md
- src/Config.php
- src/ConfigInterface.php
- test/ConfigTest.php
Added `toArray()` method to `ConfigInterface` to provide a mechanism for fetching configuration without needing to configure the service manager. This will be useful in particular for `Zend\ModuleManager\Listener\ServiceListener`, which primarily needs to aggregate and merge configuration *prior* to creating a new instance of a plugin manager.
An implementation was added to the `Config` class, along with tests.
> Add method for retrieving configuration to ConfigInterface

- src/ServiceManager.php
- test/ServiceManagerTest.php
Previous behavior of the service manager allowed specifying aliases when creating the `shared` configuration. Prior to this patch, that did not work with the refactored code.
This patch updates the code to check for a cached service under the _requested_ service name, not the _resolved_ service name, which allows specifying sharing configuration based on aliases.
Internally, it caches up to twice:
- If the resolved service name is supposed to be shared, it will cache under the resolved name.
- If the requested service name is supposed to be shared, it will cache under the resolved name.
This allows having separate instances based on service name.
(Issue created due to observed issue when refactoring zend-view to use the dev-develop branch of zend-servicemanager.)
> Cache by requested service name

- src/ServiceManager.php
- test/AbstractPluginManagerTest.php
Prior to this patch, calling `withConfig()` on a plugin manager would reset the `creationContext` to the plugin manager itself — instead of retaining the original creation context. This patch overrides the `withConfig()` method to set the creation context to the original within the cloned instance.
> Ensure plugin manager creation context travels with clone

- src/ServiceManager.php
- test/ServiceManagerTest.php
With the most recent changes to allow unshared aliases, aliases to explicitly registered services no longer worked. This patch adds logic to get() to check if:
- the alias is shared, AND
- the resolved service is present
and, if so, registers the service under the alias, returning it.
> Ensure aliases can reference explicit services

- README.md
- benchmarks/BenchAsset/AbstractFactoryFoo.php
- benchmarks/BenchAsset/FactoryFoo.php
- benchmarks/BenchAsset/Foo.php
- benchmarks/FetchServices.php
- composer.json
This PR adds the benchmarks using [athletic](https://github.com/polyfractal/athletic) framework. The benchmarks are based on the develop branch, containing the ZF3 service manager.
When merged, I'll change it to work in master so we can have a comparison of the performance.
> Add the benchmarks

- doc/book/migration.md
- src/ServiceManager.php
- test/CommonServiceLocatorBehaviorsTrait.php
In updating zend-mvc to v3 of zend-servicemanager, I ran into a subtle issue: `has()` does not look in abstract factories by default, and requires that you pass an additional flag, `$checkAbstractFactories`, with a boolean true value, if you want to test if an abstract factory can resolve the given `$name`.
This breaks the Liskov Substitution Principal, as it means that the behavior of `has()` depends on how the ServiceManager is configured. Users then must be aware that an abstract factory might supply a dependency, and cannot rely on `has()` per the container-interop contract to work for the specific use case of zend-servicemanager.
As such, this patch removes the flag, and checks abstract factories whenever a service or factory matching the provided `$name` is not found.
> Removed $checkAbstractFactories flag from has()

- CHANGELOG.md
- doc/book/configuring-the-service-manager.md
- doc/book/migration.md
- src/AbstractFactoryInterface.php
- src/AbstractPluginManager.php
- src/DelegatorFactoryInterface.php
- src/Factory/AbstractFactoryInterface.php
- src/FactoryInterface.php
- src/InitializerInterface.php
- src/ServiceManager.php
- test/AbstractPluginManagerTest.php
- test/CommonServiceLocatorBehaviorsTrait.php
- test/TestAsset/FailingAbstractFactory.php
- test/TestAsset/NonAutoInvokablePluginManager.php
- test/TestAsset/SimpleAbstractFactory.php
- test/TestAsset/V2ValidationPluginManager.php
This patch provides a number of features to allow us to provide forwards compatibilty in v2, as well as backwards compatibility with v2 code.
This patch renames the `canCreateServiceWithName()` method to `canCreate()`.  This ensures there are no overlapping methods between the v2 and v3 interfaces.
The v3 factory and initializer interfaces were all pushed under new namespaces, and, as such, have zero overlap with the existing v2 interfaces. However, the v2 interfaces cannot be used currently with v3, meaning any factories or initializers that implemented the interfaces (vs using callables) are de facto incompatible with v3.
This patch reintroduces the v2 interfaces, and modifies them to inherit from the v3 interfaces. This provides a forwards compatibility feature: developers can …
> Forward compatibility features

- src/AbstractPluginManager.php
- src/Factory/InvokableFactory.php
- test/AbstractPluginManagerTest.php
- test/Factory/InvokableFactoryTest.php
- test/TestAsset/InvokableObject.php
This patch provides forwards compatibility features for the v2 series to allow users to update their code for use with v3 prior to an actual migration.
This patch modifies the `AbstractPluginManager` constructor to allow the following combination of arguments:
- No arguments (current behavior).
- Single `ConfigInterface` argument (current behavior); used to configure the instance.
- Single `ContainerInterface` argument (v3 behavior); sets the "parent" locator/"creation context"
- `ContainerInterface` as first argument, array as second (v3 behavior); sets the "parent" locator/"creation context", and uses the second argument to configure the instance.
These changes allow developers the ability to continue to use existing plugin managers when upgrading to v3 (though they will also need to …
> Forwards-compatibility changes

- doc/book/migration.md
> change withConfig() to configure() in migration doc

- doc/book/quick-start.md
If we request an instance with the `build()` method shouldn't we get a new instance for every call? If so, the comparison should print `false` instead of `true`, shouldn't it?
> Error in Quick-Start with build() method

- src/Exception/ExceptionInterface.php
- src/Exception/ServiceNotFoundException.php
> Use container-interop exception interfaces

- .travis.yml
- src/Exception/InvalidServiceException.php
- src/Factory/InvokableFactory.php
- test/Factory/InvokableFactoryTest.php
This patch provides a couple of fixes for behavior/incompatibilities observed in the v2 series when adapting existing components to work against both v2 and v3:
- First, it adds `InvalidServiceException`. This particular exception exists on v3, but not v2, and is thrown by the v3 implementation of `InvokableFactory`. As such, v2 requires it.
- Second, it alters the behavior of `InvokableFactory::createService()` to accommodate the two possible behaviors that exist in v2 (but not v3):
- The original behavior, in which a `name => factory` configuration is used, results in `$canonicalName` being a normalized name, and `$requestedName` being the name as passed to `get()` — which would be the class name to use.
- In v2, if an alias was used, `$canonicalName` is the *resolved alias*, which will …
> InvokableFactory behavior for v2 series

- src/Factory/InvokableFactory.php
- test/Factory/InvokableFactoryTest.php
In v2, options passed via the second argument to `AbstractPluginManager::get()` are passed to factory *constructors*; the factory must then determine whether or not to use them when creating the object instance.
This patch updates `InvokableFactory` to add a constructor that can accept creation arguments; `createService()` will then pass them to `__invoke()` when present.
> Allow creation options as passed via v2 factories.

- src/ServiceManager.php
- test/ServiceManagerTest.php
This patch fixes alias resolution for version 2 to ensure (a) forwards compatibility with version 3, and (b) proper resolution of aliases with regards to services resolved by abstract factories.
The original report in #66 was that doing the following did not work correctly:
```php
$sm->setAlias('foo', InvokableObject::class);
$sm->setFactory(InvokableObject::class, InvokableFactory::class);
$result = $sm->get('foo');
```
When the above code was executed, `InvokableFactory::createService()` was receiving arguments that it could not use, and thus raising an exception. On inspection, what I discovered was that the `$cName` provided as a normalized version of the resolved alias — and due to normalization, would not resolve to a fully qualified class name. This was due to the fact that the SM …
> Alias resolution fixes

- src/ServiceManager.php
- test/ServiceManagerTest.php
Release 2.7.3 broke a use case of Alias of Alias without using an already canonicalized name.
Added a test that recreates the problem, and I think a fix that doesn't seem to break any other tests and achieves what I hope is the right thing. 
All comments welcome, but we'd appreciate getting a fix on this soon.
Thanks
> Broken use case using Alias of Alias

- src/Config.php
- test/ConfigTest.php
- test/TestAsset/ExtendedConfig.php
...and simplify config implementation
> Remove Zend\Stdlib dependency

- test/AbstractPluginManagerTest.php
- test/TestAsset/V2v3PluginManager.php
I'm sure I'm doing something really, really dumb, but I'm trying to follow the [migration docs](https://github.com/zendframework/zend-servicemanager/blob/develop/doc/book/migration.md#migration-example) and from what I've read this test should pass. Instead I get:
```
1) ZendTest\ServiceManager\AbstractPluginManagerTest::testV2v3PluginManager
Zend\ServiceManager\Exception\ServiceNotFoundException: An alias "ZendTest\ServiceManager\TestAsset\InvokableObject" was requested but no service could be found.
/Users/matt/www/zend-servicemanager/src/ServiceManager.php:551
/Users/matt/www/zend-servicemanager/src/AbstractPluginManager.php:161
/Users/matt/www/zend-servicemanager/test/AbstractPluginManagerTest.php:342
```
From what I can tell ServiceManager v2 is still looking up factories by their …
> Test for v2-v3 PluginManager migration

- src/AbstractPluginManager.php
- src/Factory/InvokableFactory.php
- test/AbstractPluginManagerTest.php
- test/TestAsset/FooPluginManager.php
I've run into a problem where multiple calls to `get('foo', $options)` on a plugin manager are not setting the options on subsequent calls. I'm an using an alias to `InvokableFactory`, as recommended in the v2-v3 [migration docs](https://github.com/zendframework/zend-servicemanager/blob/master/doc/book/migration.md#migration-example).
This PR addresses that for v2 by adding the `MutableCreationOptionsInterface` to `InvokableFactory`. 
Note that this _only_ works when the plugin manager has been marked `$shareByDefault = false`. I am unable to determine if that is expected behaviour.
> Added setCreationOptions() to InvokableFactory

- src/Test/CommonPluginManagerTrait.php
Adds test trait from #93, allowing plugin manager migration tests to run under by 2.7 and 3.0
> Backported CommonPluginManagerTrait from v3

- src/ServiceLocatorInterface.php
- src/ServiceManager.php
Forward compatibility change, `ServiceLocatorInterface` now extends `ContainerInterface`, and therefore `ServiceManager` no longer implements the `ContainerInterface`
> Changed the way ContainerInterface is implemented

- test/AbstractPluginManagerTest.php
- test/CommonServiceLocatorBehaviorsTrait.php
- test/Factory/InvokableFactoryTest.php
- test/Proxy/LazyServiceFactoryTest.php
- test/ServiceManagerTest.php
unit tests update, phpunit set getMock on deprecated
https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.4.0#changes
> phpunit removed getMock

- src/ServiceManager.php
i found on my fail pull request:
https://travis-ci.org/bjyoungblood/BjyAuthorize/jobs/144009025
Cannot use Zend\ServiceManager\Initializer\InitializerInterface as InitializerInterface because the name is already in use in `ServiceManager.php` on line 27
im not realy sure about the alias name to resolve problem, so im open for other solutions.
> InitializerInterface already in use

- .travis.yml
- composer.json
Per our other repositories, and in preparation for the next minor version.
> Updated to mark PHP 5.6 as minimum supported version

- src/ServiceLocatorInterface.php
- test/Exception/CyclicAliasExceptionTest.php
- test/TestAsset/PreDelegator.php
This PR
💁 Ran
```
$ composer global require friendsofphp/php-cs-fixer:2.0.0-alpha
$ php-cs-fixer fix --using-cache=no --rules=no_unused_imports .
```
> Fix: Remove unused imports

- doc/book/migration.md
`Zend\ServiceManager\Initializer\InitializerInterface::__invoke()`'s docblock says that it does not return the instance, so the migration documentation should not either.
FWiW, the V2 example probably should't return `$instance` either. However, the V2 interface says that it returns `mixed`, even though v2's `ServiceManager` doesn't do anything with it in `doCreate()`. Wasn't sure what to do with the V2 one, so left it alone.
> [docs] Don't return $instance in initializer callable doc

- composer.json
- doc/book/console-tools.md
- src/Tool/ConfigDumperCommand.php
- test/Tool/ConfigDumperCommandTest.php
Per experiments with @GeeH, we discovered that piping back to the same file will not work, as `>` overwrites immediately, meaning the config file is blank when the tool starts to execute. As such, this patch updates the command to write back to the original file.
> Re-work ConfigDumperCommand to write back to provided config file

- doc/book/cookbook/factories-vs-abstract-factories.md
- mkdocs.yml
This patch adds a cookbook to the documentation, and provides a document outlining the pros and cons of abstract factories vs factories (and/or using the former as the latter).
> Wrote document resolving #148

- src/Factory/InvokableFactory.php
- test/Factory/InvokableFactoryTest.php
This pull request removes the `class_exists()` call with `$canonicalName` argument from v2 `Zend\ServiceManager\Factory\InvokableFactory::createService()` method (#61).
Since #69 changed the service alias resoultion, InvokableFactory recieves FQCN via $requestedName parameter.
`class_exists($canonicalName)` produces an extra autoloader call which is either redundant (as $canonicalName now contains a canonicalized service name if actual name or alias is given), or may lead to an unexpected behaviour, as `$canonicalName` may be an actual name of another class. In that case it can be pulled by autoloader, making the factory produce an object of that class.
A positive test case for creating an object of $canonicalName class is converted to a negative one, expecting a …
> Removing class_exists($canonicalName) call from InvokableFactory v2

- src/AbstractPluginManager.php
- src/Factory/InvokableFactory.php
- test/AbstractPluginManagerTest.php
- test/TestAsset/Baz.php
I'm afraid you might consider this a BC break because of changing the signature of `setCreationOptions()`
See #159
> Fix #159 by resetting creation options to NULL

- doc/book/console-tools.md
- src/Tool/ConfigDumperCommand.php
- test/Tool/ConfigDumperCommandTest.php
Modifies the tool slightly to allow it to create the specified config file if it does not currently exist.
> Allow the generate-deps-for-config-factory to create the specified config file

- CHANGELOG.md
- composer.json
- doc/book/psr-11.md
- mkdocs.yml
- src/ServiceLocatorInterface.php
- test/ServiceManagerTest.php
This patch updates the `container-interop/container-interop` constraint to `^1.2`, and explicitly adds `psr/container` with a constraint of `^1.0`; this immediately allows `Zend\ServiceManager\ServiceManager` to be used as a PSR-11 container.
Moreover, this patch provides a test validating that assertion.
> Add PSR-11 support to `ServiceManager`

- doc/book/configuring-the-service-manager.md
- doc/book/cookbook/factories-vs-abstract-factories.md
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
> spelling fixes

- benchmarks/BenchAsset/AbstractFactoryFoo.php
- benchmarks/BenchAsset/FactoryFoo.php
- src/AbstractFactory/ConfigAbstractFactory.php
- src/AbstractFactory/ReflectionBasedAbstractFactory.php
- src/AbstractPluginManager.php
- src/Config.php
- src/Exception/CyclicAliasException.php
- src/Proxy/LazyServiceFactory.php
- src/ServiceLocatorInterface.php
- src/ServiceManager.php
- src/Test/CommonPluginManagerTrait.php
- src/Tool/ConfigDumper.php
- src/Tool/ConfigDumperCommand.php
- src/Tool/FactoryCreator.php
- src/Tool/FactoryCreatorCommand.php
- test/AbstractFactory/ReflectionBasedAbstractFactoryTest.php
- test/AbstractPluginManagerTest.php
- test/CommonServiceLocatorBehaviorsTrait.php
- test/LazyServiceIntegrationTest.php
- test/Proxy/LazyServiceFactoryTest.php
- test/TestAsset/V2ValidationPluginManager.php
- test/TestAsset/V2v3PluginManager.php
- test/Tool/ConfigDumperCommandTest.php
- test/Tool/ConfigDumperTest.php
- test/Tool/FactoryCreatorCommandTest.php
- test/Tool/FactoryCreatorTest.php
As @kynx noticed in #196 we can import internal PHP functions to get the same optimisation in function calls. Changes in this PR are made by sniff from dev of [`zend-coding-standard`](https://github.com/zendframework/zend-coding-standard/pull/1/commits/19e353bb65a32774e9fd40d901587f95e777572b) library and it supersedes #196.
/cc @smuggli @kynx @MichaelGooden @Ocramius @weierophinney
> Import PHP internal functions

- src/AbstractFactory/ConfigAbstractFactory.php
- src/AbstractFactory/ReflectionBasedAbstractFactory.php
- src/Config.php
- src/ServiceManager.php
Those optimizations target improving OPCODES.
> Optimize PHP function calls

- src/Tool/ConfigDumperCommand.php
- src/Tool/FactoryCreatorCommand.php
ref: http://maettig.com/code/php/php-performance-benchmarks.php#empty
> replace count() usage to empty() when possible

- src/ServiceManager.php
- test/ServiceManagerTest.php
ServiceManager v2 supported configuring factories to callable strings of the form `'Class::Method'`, as a concise alternative to `['Class', 'Method']`.
ServiceManager v3 continues to support this for PHP 7, but for some reason, the feature breaks in PHP 5.6.
This pull request includes a possible fix as well as a test that demonstrates the problem; without my proposed code changes to the ServiceManager, the test dies with a fatal error in PHP 5.6, but passes in PHP 7.
If there is a more elegant solution, I would welcome feedback. If this support is being dropped intentionally, we should at least find a way to fail more gracefully.
> Fix problem with string callables failing in PHP 5.6.

- .travis.yml
- src/AbstractPluginManager.php
- test/AbstractPluginManagerTest.php
- test/TestAsset/FactoryUsingCreationOptions.php
If you use an own factory, the creationOptions wont get resetted.
There is a check, that if the factory is an `InvokableFactory`, that `$factory->setCreationOptions(null)` is being called, because it has the `array $options` as optional parameter.
The problem is, that the method itself is not documented and therefore some factories might have required `$options` parameter in the method declaration.
Any ideas of how we could reset those options for factories with required `$options` parameter?
Or should those factories handle the reset of the `$creationOptions` property itself?
> [BUG] Own factories for plugins wont reset creationOptions

- src/AbstractPluginManager.php
- test/AbstractPluginManagerTest.php
- test/TestAsset/FactoryUsingCreationOptions.php
Per https://github.com/zendframework/zend-servicemanager/issues/159#issuecomment-349339218, the updates in #205 broke a previously fixed edge case whereby `AbstractPluginManager::createServiceViaCallback()` would inject a `null` value to a factory's `setCreationOptions()` method if no instance options were provided; it instead passed an empty array, which broke a number of plugins that relied on a null value being present.
This patch does the following:
- Adds a regression test for the behavior.
- Modifies `AbstractPluginManager::createServiceViaCallback()` to have three distinct behaviors surrounding creation options, in the following order:
- if the factory is an `InvokableFactory`, it tests if the creation options are an array or non-empty; if not, it passes a `null` value to …
> Ensure a `null` value is passed to `setCreationOptions` instead of empty array

- src/ServiceManager.php
In `develop` branch the minimum PHP is 7.1, so this fix is superfluous.
> Remove PHP < 7 fix

- benchmarks/HasBench.php
- benchmarks/SetNewServicesBench.php
- src/AbstractPluginManager.php
- src/Exception/ContainerModificationsNotAllowedException.php
- src/Exception/CyclicAliasException.php
- src/Exception/InvalidArgumentException.php
- src/ServiceManager.php
- test/CommonServiceLocatorBehaviorsTrait.php
- test/Exception/CyclicAliasExceptionTest.php
- test/ServiceManagerTest.php
This PR is about performance of the setter APIs (or injector APIs if you like) as well as has(). Here's the current comparison report. Thanks @dantleech for faster than light fix.
benchmark: SetNewServicesBench
+------------------------+--------------------+------------------+--------+
| subject                | suite:develop:mean | suite:PR221:mean | gain   |
+------------------------+--------------------+------------------+--------+
| benchSetService        | 1.924µs            | 0.655µs          |  2,94x |
| benchSetFactory        | 4.183µs            | 1.226µs          |  3,41x |
| benchSetAlias          | 11.222µs           | 1.872µs          |  5,99x |
| benchSetAliasOverrided | 34.617µs           | 1.876µs          | 18,45x | …
> Performance enhancements for has(), setService(), setFactory(), setShared(), setAlias(), setInvokableClass() and configure()

- src/ServiceManager.php
- test/CommonServiceLocatorBehaviorsTrait.php
> Can you try and open a new PR just with the test and the proposed fix?
Of course. This PR provides tests and a bug fix for mapAliasesToTargets(). The fix does not cost performance. :)
> Fix alias resolution #221

- src/AbstractFactory/ReflectionBasedAbstractFactory.php
- test/AbstractFactory/ReflectionBasedAbstractFactoryTest.php
- test/AbstractFactory/TestAsset/ClassWithTypehintedDefaultValue.php
Per #239, currently when an argument is type-hinted but has a default value (typically `null`), the factory raises an exception about not being able to retrieve the value from the container. In such cases, we can use the default value for the argument during injection.
Fixes #239.
> Use default values for type-hinted arguments if type not found in container

- test/CommonServiceLocatorBehaviorsTrait.php
- test/TestAsset/AbstractFactoryFoo.php
- test/TestAsset/Foo.php
- test/TestAsset/PassthroughDelegatorFactory.php
Adds a test addressing the issue described in #236. 
/**
* The ServiceManager can change internal state on calls to get,
* build or has, latter not currently. Possible state changes
* are caching a factory, registering a service produced by
* a factory, resolving an alias and so on.
*
* This tests performs three consecutive calls to build/get for
* each registered service to push the service manager through
* all internal states, thereby verifying that build/get/has
* remain stable through the internal states.
*/
The test does not make any assumptions about particular internal states the ServiceManager has or might have. The ServiceManager is treated as a blackbox in order to make sure, that the test is agnostic to possible future changes to the implementation of internal states.
> Adds test for issue #236

- src/ServiceManager.php
- test/ServiceManagerTest.php
There was an error in the testcase `testAbstractFactoryShouldBeCheckedForResolvedAliasesInsteadOfAliasName`
where the returnValueMap of phpunit was used wrong. This caused a false positive. The test was returning an
array which is interpreted as `TRUE`.
I discovered this when I added the `testResolvedAliasFromAbstractFactory`, which should do the opposite form the
earlier mentioned testcase.
Beside that I found a way that the servicemanager was returning `null` instead of returning false when the last fallback
on abstract factories failed.
I'm not sure if the `testAbstractFactoryShouldBeCheckedForResolvedAliasesInsteadOfAliasName` is still doing what was intended to do. So that might be a point of discussion.
> Improved tests aliases with abstract factories.

- composer.json
- composer.lock
- test/ContainerTest.php
During the work on expressive @weierophinney set shared service to `false`  for `ResponseInterface` service. It means every call of the `get` method on the service manager will create new instance of `ResponseInterface`. Please see:
https://github.com/zendframework/zend-expressive/pull/543#discussion_r165378017
In this PR I'd like to check if `shared` services work correctly with all types of services and then provide the same functionality for other containers:
- [zend-pimple-config](https://github.com/zendframework/zend-pimple-config) - see: https://github.com/zendframework/zend-pimple-config/pull/6
- [zend-auradi-config](https://github.com/zendframework/zend-auradi-config)
to have exactly the same behaviour with different container managers.
This is just basics: I'm testing here …
> Added more test for shared services (aliases, factories, invokables)

- CHANGELOG.md
- src/AbstractPluginManager.php
- test/AbstractPluginManagerTest.php
- test/TestAsset/FooStaticFactory.php
When a plugin manager uses a static class method as a factory (i.e. `FactoryClass::factoryMethod`), as of release 2.7.10, it causes an undefined variable notice to be thrown due to an uncovered else case. This pull request provides a test case to demonstrate the problem as well as a fix. This problem does not appear to exist in the 3.x code, so it is presumably a side effect of backporting to 2.7. However, for projects depending on earlier versions of the service manager, it can be a significant problem and should be corrected -- that is why I am targeting this PR against the release-2.7 branch.
> Undefined $factory notice fix

- CHANGELOG.md
- src/AbstractPluginManager.php
- src/PsrContainerDecorator.php
- test/AbstractPluginManagerTest.php
- test/PsrContainerDecoratorTest.php
Enables plugin managers to accept non-interop psr containers as creation
context and transparently wrap as interop for backward compatibility
Provide a narrative description of what you are trying to accomplish:
This PR enables plugin managers extending from abstract plugin manager to accept non-interop psr containers as creation context in a backward compatible manner. It is useful when alternative containers are used eg with zend-expressive.
Decoration is necessary since FactoryInterface typehints against interop and won't work with pure PSR https://github.com/zendframework/zend-servicemanager/blob/0aea76faf40350852fd6570cb4c1eb60a18ac872/src/Factory/FactoryInterface.php#L10 https://github.com/zendframework/zend-servicemanager/blob/0aea76faf40350852fd6570cb4c1eb60a18ac872/src/Factory/Fac …
> Introduce psr to interop container decorator for plugin managers

- src/ServiceManager.php
Submitted is a minor typographical fix for the docblock of ServiceManager::resolveAliases() which causes an exception when using for zf-annotations (and likely other doctrine annotation powered tooling).
```
Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: 
[Semantical Error] The annotation "@returns" in method Zend\ServiceManager\ServiceManager::resolveAliases() was never imported. 
Did you maybe forget to add a "use" statement for this annotation? in /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54
```
To reproduce:
1. Check out zend-framework-skeleton
2. Add zf-annotations to composer and config/application.php ( or in a module )
3. Attempt to access any route, and see the above error
Expected Behavior: …
> docbock fix for ServiceManager::resolveAliases(): @return, not @returns; Causes bug in zf-annotation

- src/Proxy/LazyServiceFactory.php
> define $initializer variable definition only when there is $this->servicesMap[$name] at LazyServiceFactory

- CHANGELOG.md
- src/AbstractFactory/ReflectionBasedAbstractFactory.php
- test/AbstractFactory/ReflectionBasedAbstractFactoryTest.php
- test/AbstractFactory/TestAsset/ClassWithPrivateConstructor.php
I noticed that when using the `ReflectionBasedAbstractFactory`, it chokes when classes with `private` constructors are used. These types of classes should be ignored from the start, so I've updated `canCreate` to return `false` where any class has a `private` constructor.
> ReflectionBasedAbstractFactory should not be expected to instantiate private constructors
